### ISSUE TITLE
Footer should be centered.

### ISSUE THREAD

**Issue by luziusmeisser** [aktionariat/www#12]

**Comment by luziusmeisser** [comment]
![image](https://user-images.githubusercontent.com/3128389/105820756-3f91af00-5fba-11eb-88ea-ec8c37906957.png)

**Comment by luziusmeisser** [comment]
Not sure what is happening here. :)

**Comment by muratogat** [comment]
"ul" tag was creating automatting padding from left
I removed it, so now at least left and right padding are the same.
Still the wrapping and the list dashes seems a bit off on mobile.

<img width="457" alt="Screenshot 2021-01-26 at 12 52 16" src="https://user-images.githubusercontent.com/1083315/105841743-6b6e5e00-5fd5-11eb-88cf-360fe3f2ed62.png">

On bigger browsers, looks fine.

<img width="488" alt="Screenshot 2021-01-26 at 12 54 43" src="https://user-images.githubusercontent.com/1083315/105841896-b4261700-5fd5-11eb-8374-f260a6da0c85.png">
