### ISSUE TITLE
Refine blog

### ISSUE THREAD

**Issue by muratogat** [aktionariat/www#15]
Currently, the blog is very basic and I do not find it very pleasant to look at it. Maybe Lazar has some ideas? Would it help to add a header image or so? Or a sidebar with a topic navigation? Unsure. :)

**Comment by muratogat** [comment]
I like the idea of having a side menu for content navigation

Some examples below

<img width="1108" alt="Screenshot 2021-01-26 at 13 07 50" src="https://user-images.githubusercontent.com/1083315/105843116-8a6def80-5fd7-11eb-8ea7-e9faf8ae0ccd.png">

<img width="1075" alt="Screenshot 2021-01-26 at 13 09 00" src="https://user-images.githubusercontent.com/1083315/105843203-b1c4bc80-5fd7-11eb-8b8d-b75a017c76de.png">

**Comment by lzrj** [comment]
@pansay I think the interview questions have the same issue as mentioned on slack: 1.4rem + font-weight: 900 don't mix well, I would either make the questions corporate yellow and normal font weight, or you start using font-weight 600 or 700 only here...

![image](https://user-images.githubusercontent.com/78359118/110478468-aee3de00-80e4-11eb-9442-54cc3df1801c.png)

**Comment by pansay** [comment]
@lzrj the bold issue is solved I think (?)

for the rest you tackle that as part of the general redesign right?

**Comment by lzrj** [comment]
@pansay yes, exactly.
