### ISSUE TITLE
Add a "book a free call" button to main page.

### ISSUE THREAD

**Issue by muratogat** [aktionariat/www#17]
Like lexr.ch has on its front page. Christian says they get a lot of appointments that way. The person responsible for doing the calls should be Nicola.

**Comment by muratogat** [comment]
"Book a free call" is a very nice call-to-action. This can be the main action mentioned in the Sitemap for now.

Ideally we could have a separate page with a contact form, address and a phone number, also like https://www.lexr.ch/contact/

If we are OK with this, I need to add it to the Sitemap document. The "Contact" link should also be added to the menu and footer.

**Comment by luziusmeisser** [comment]
I prefer keeping the number of pages low and suggest to merge the "about" and "contact" page into one. So visitors can see who we are and get in touch with us, with the contact information and buttons first and the team below.

**Comment by pansay** [comment]
the button on https://www.lexr.ch/ merely leads to

https://www.lexr.ch/contact/#global-cta
which has several things including contact form, and for the call a calendar widget. I assume this would need to be configured to someone's calendar.

**Comment by luziusmeisser** [comment]
Yes, that would probably be Nicos Calendar

**Comment by luziusmeisser** [comment]
New offer section?

<p>
              Are you investor or founder of a promising Swiss company, and you think its shares deserve to be traded in an open market? Get in touch!
            </p>
            <p>
              We offer a convenient and incremental path forward:

              1. Schedule a call with us to gain access to our <a href="https://dashboard.akionatiat.com">Corporate Dashboard</a>.
              2. Import your traditional shareholder registry, enabling your shareholders to see their holdings in the Aktionariat portfolio app. This already provides additional value.
              3. As soon as you feel ready, propose to the general assembly to adjust your articles of assocation and the shareholder agreement (if there is one).
              4. Shareholders are free to request a tokenization of their shares through the portfolio app. Doing so makes it possible to digitally transfer them.
              5. <b>Create an open market</b>, allowing shareholders to trade them at any time and boosting their value.

              The journey starts with a click on the button below.
            </p>
