### ISSUE TITLE
Switch page title position for every page

### ISSUE THREAD

**Issue by lzrj** [aktionariat/www#26]
While tab browsing, now I see «Aktionariat – [title]» while the part after the dash gets cut off. I would switch it around, eg. 
Blog – Aktionariat
Terms – Aktionariat
Investor's Page – Aktionariat

**Comment by pansay** [comment]
on the other hand, what's the use case here? we don't have that many pages and we're not an e-commerce website. why would a normal user have several of our pages opened at once?
and conversely, they could also have "Blog - Aktionariat", and... 10 other "Blog..." tabs.

**Comment by luziusmeisser** [comment]
They already know it’s us thanks to the favicon. Also, I often have the dashboard open in one tab and the investor page in another.
