### ISSUE TITLE
Investor relations styling (aktionariat.com)

### ISSUE THREAD

**Issue by lzrj** [aktionariat/www#35]
Optimisation of the current investor relation page – editorial, layout, etc.

**Comment by lzrj** [comment]
![210208_investors](https://user-images.githubusercontent.com/78359118/107247105-38928400-6a31-11eb-8b77-ef60a3ab8b05.png)

### Main take-aways
## Layout

- 13 columns with 10px spacing in-between (13 x 138.462 px + 12 x 10 px = ~1920 px in this example)
- So a content-column should be ~135-140px wide with ~10px spacing, depending on the device
- mobile layout will follow (probably ~5-7 columns + 2 margin and all content in one vertical line)

# Content widths

- main content area: 9 columns + multiple columns margin depending on the viewport, here: 2 columns margin each (L+R)
- Aktionariat logo: 4 columns (but aligned on the first letter «A», not the circled logo)
- text boxes: 5 columns
- portrait: 3 columns
- graphs: 7 columns + axes offset
- widget: 4 columns

## Fonts, Sizes (pt = px) & Colours

- background gradient, from top to bottom: RGB(0, 0, 10) -> RGB (34, 32, 80)
- H1: 134 pt Montserrat Black #efcb68
- H2 80 pt Montserrat Black #efcb68
- H3: 36 pt Montserrat Regular #ffffff (name, table/chart titles)
- everything else: 24 pt Montserrat Regular #ffffff
- links: #efcb68
- lines: 1.5 pt thick #ffffff or #efcb68 depending on highlight
- widget bg: #333333
- widget text: #ffffff, #000000 & #efcb68

**Comment by luziusmeisser** [comment]
Very nice! Only the two widgets do not seem to integrate very well. 

Maybe we should:

- move them to the left of the text
- Make them transparent? ( possible? )

**Comment by lzrj** [comment]
Thank you!

No, they don't, that's why I created a separate issue just for the widget redesign, I consider those now just an intermediate draft until I come up with something better – but I wanted to upload something for the investor's page already. 

Funny you say transparent, I had them like that already and it looked rather nice.

**Comment by lzrj** [comment]
Already much nicer.

![210209_widget](https://user-images.githubusercontent.com/78359118/107387854-82dd3900-6af5-11eb-8bed-900673a235a5.png)

**Comment by lzrj** [comment]
mobile/responsive layout to follow

**Comment by lzrj** [comment]
That's how I imagine a responsive layout might look like:

- 5 column wide content (5 x 140px + 40px margins)
- everything vertically in order
- widgets also 5 columns wide
- portrait 3 columns wide
- y-axis of charts also outside column like on desktop

![210215_investors_mobile](https://user-images.githubusercontent.com/78359118/108041989-8ade3100-703f-11eb-94b9-f12ea1c26a51.png)
![Screenshot 2021-02-16 at 10 04 55](https://user-images.githubusercontent.com/78359118/108042407-06d87900-7040-11eb-834b-86d7c63a2a66.png)
![Screenshot 2021-02-16 at 10 05 32](https://user-images.githubusercontent.com/78359118/108042418-08a23c80-7040-11eb-866a-4714065f3be7.png)

**Comment by luziusmeisser** [comment]
@lzrj : Great work!

@pansay : when do you think we can see this live?
