### ISSUE TITLE
Mockup to approach banks with "send instructions" button idea

### ISSUE THREAD

**Issue by lzrj** [aktionariat/www#38]

**Comment by lzrj** [comment]
@luziusmeisser Which banks/services would you like included in the mockup? Couldn't find the picture from your drawing on Signal...

**Comment by lzrj** [comment]
+ Seba Bank https://www.seba.swiss
+ Sygnum https://www.sygnum.com
+ Bitcoin Suisse https://www.bitcoinsuisse.com

**Comment by lzrj** [comment]
What do you think @luziusmeisser?

![210209_widget_banks](https://user-images.githubusercontent.com/78359118/107386118-d6e71e00-6af3-11eb-93ac-f12495dbd956.png)

**Comment by luziusmeisser** [comment]
Thanks, looks nice!
One detail: instead of “Send instructions”, it would be better to say “Instruct my Bank”.

Analogously, it should also say “Connect to my wallet” with “my” instead of “a”.

**Comment by lzrj** [comment]
Here you go:
![210209_widget_banks_2](https://user-images.githubusercontent.com/78359118/107398334-cfc60d00-6aff-11eb-94eb-8a407ea2f87c.png)

**Comment by luziusmeisser** [comment]
Danke!
